name: Update VS Code Windows 64-bit Installer

on:
  schedule:
    - cron: '0 0 * * *'  # 每天零点执行

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest VS Code version
        id: get-version
        run: |
          VERSION=$(curl -s https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user | grep -oP '(?<=code-stable-)(.*?)(?=.exe)')
          echo "::set-output name=version::$VERSION"

      - name: Download VS Code installer
        run: |
          VERSION="${{ steps.get-version.outputs.version }}"
          curl -L -o "VSCodeSetup-${VERSION}-x64.exe" "https://update.code.visualstudio.com/${VERSION}/win32-x64-user/VSCodeSetup-${VERSION}-x64.exe"

      - name: Commit and push new installer
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update VS Code installer to version ${VERSION}"
          files: |
            VSCodeSetup-${VERSION}-x64.exe

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.Tb_1234 }}
