name: Update VS Code Windows 64-bit Installer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点执行（北京时间为8点）

jobs:
  update-vscode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download VSCode Installer
      run: |
        curl -LJO https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user

    - name: Install gh CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update -y
        sudo apt install gh -y

    - name: Login to GitHub CLI
      env:
        PAT: ${{ secrets.PAT_TOKEN }}
      run: |
        gh auth login --with-token <(echo $PAT)

    - name: Commit and Push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add "VSCode-latest-win32-x64-setup.exe"
        git commit -m "Update to latest VSCode version"
        gh repo edit --push