permissions:
  contents: write

name: Update VScode with LFS

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Update_VScode:
    env:
      PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install Git LFS
      run: |
        # Install Git LFS if not already installed
        choco install git-lfs -y
        # Initialize Git LFS in the repository
        git lfs install

    - name: Download VScode
      shell: pwsh
      run: |
        $webRequest = [System.Net.WebRequest]::Create("https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user")
        $webRequest.Method = 'HEAD'
        $webRequest.AllowAutoRedirect = $false
        $response = $webRequest.GetResponse()
        $locationHeader = $response.Headers["Location"]
        $response.Close()
        Invoke-WebRequest -Uri $locationHeader -OutFile "VScodeSetup.exe"

    - name: Track VScodeSetup.exe with Git LFS
      run: |
        # Track the file with Git LFS
        git lfs track "VScodeSetup.exe"

    - name: Add and Commit with LFS
      run: |
        git config --local user.email "tb1145@outlook.com"
        git config --local user.name "Tb114"
        # Add the tracked file to the staging area
        git add VScodeSetup.exe
        # Commit the changes
        git commit -m "Automatically updated VScodeSetup.exe using Git LFS"

    - name: Push changes to GitHub
      run: |
        # Push the changes including the LFS objects
        git push origin main

    - name: Clean up
      run: |
        # Optionally, remove the file after pushing
        rm VScodeSetup.exe
