name: Update VS Code Windows 64-bit Installer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点执行（北京时间为8点）

jobs:
  update-vscode:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download VSCode Installer
      run: |
        $url = "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
        Invoke-WebRequest -Uri $url -OutFile "VSCode-latest-win32-x64-setup.exe"

    - name: Commit and Push
      env:
        PAT: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add "VSCode-latest-win32-x64-setup.exe"
        git commit -m "Update to latest VSCode version"
        git push https://${{ secrets.PAT_TOKEN }}@github.com/Tb114/VScode-Auto-Sync.git HEAD