permissions:
  contents: write
name: VSCode Sync
on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:
jobs:
    X:
        env :
          PAT:  ${{ secrets.GITHUB_TOKEN }}
        runs-on: windows-latest
        steps:
        - name: Check
          uses: actions/checkout@v3
        - name: Download
          shell: pwsh
          run: |

            $webRequest = [System.Net.WebRequest]::Create("https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user")
            $webRequest.Method = 'HEAD'
            $webRequest.AllowAutoRedirect = $false
            $response = $webRequest.GetResponse()
            $headersJson = $response.Headers | ConvertTo-Json
            $locationHeader = $response.Headers["Location"]
            $response.Close()
            Invoke-WebRequest -Uri $locationHeader -OutFile "VSCodeSetup.exe"
            # 从响应中提取 'Location' 头
        - name: Push
          run: |
            &git config --local user.email "tb1145@outlook.com"
            &git config --local user.name "Tb114"
            &git add .
            &git commit -m "Automatically updated by GitHub Action"
            &git push origin main
            - name: Clear
            run: |
              rm VSCodeSetup.exe