
name: Update VS Code Windows 64-bit Installer
on:   
  workflow_dispatch:
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行一次

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new VS Code release
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          latest_version=$(curl -s https://update.code.visualstudio.com/api/update/win64/stable/version)
          echo "Latest version of VS Code: $latest_version"
          echo "::set-output name=version::$latest_version"

      - name: Download VS Code installer
        id: download_installer
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          version=${{ steps.check_release.outputs.version }}
          curl -o vscode-win64-${version}.exe -L https://update.code.visualstudio.com/api/update/win64/stable/${version}/installer
          echo "Downloaded VS Code installer version $version"

      - name: Upload installer to repository
        uses: actions/upload-artifact@v2
        with:
          name: vscode-installer
          path: vscode-win64-${{ steps.check_release.outputs.version }}.exe
