
name: test1
on:
    workflow_dispatch:
jobs:
    x:
        runs-on: windows-latest
        steps:
        - name: Check
          uses: actions/checkout@v3
        - name: download
          shell: pwsh
          run: |

            $webRequest = [System.Net.WebRequest]::Create("https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user")
            $webRequest.Method = 'HEAD'
            $webRequest.AllowAutoRedirect = $false
            $response = $webRequest.GetResponse()
            $headersJson = $response.Headers | ConvertTo-Json
            $locationHeader = $response.Headers["Location"]
            $response.Close()
            Invoke-WebRequest -Uri $locationHeader -OutFile "VSCodeSetup.exe"
            # 从响应中提取 'Location' 头
        - name: Push
          env :
            PAT:  ${{ secrets.PAT_TOKEN }}
          run: |
            &git config --global user.email "tb1145@outlook.com"
            &git config --global user.name "Tb"
            & git add .
            & git commit -m "Automatically updated VSCodeSetup.exe"
            & git push origin main